const styles = {
    container: {
      flex: 1,
      padding: 20,
      backgroundColor: '#0F172A', 
      minHeight: '100vh',
    },
    centerContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#0F172A',
      padding: 16,
    },
    header: {
      fontSize: 28,
      fontWeight: '700',
      color: '#D1B2FF',
      marginBottom: 24,
      letterSpacing: 0.5,
    },
    card: {
      backgroundColor: '#1E293B',
      borderRadius: 12,
      marginBottom: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 5,
      borderWidth: 1,
      borderColor: 'rgba(209, 178, 255, 0.1)',
    },
    cardContent: {
      padding: 20,
    },
    title: {
      fontSize: 22,
      fontWeight: '700',
      color: '#D1B2FF',
      marginBottom: 12,
      letterSpacing: 0.3,
    },
    excerpt: {
      color: '#E2E8F0',
      marginBottom: 16,
      lineHeight: 24,
      fontSize: 16,
    },
    dateContainer: {
      height: 20,
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 8,
    },
    icon: {
      width: 16,
      height: 16,
      color: '#94A3B8',
      marginRight: 8,
    },
    clockIcon: {
      marginLeft: 16,
      color: '#94A3B8',
    },
    bookmarkButton: {
        backgroundColor: '#7C3AED', // Koyu mor
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 6,
        elevation: 3,
        flexDirection: 'row',
        alignItems: 'center',
      },
      bookmarkText: {
        color: '#FFFFFF', // Beyaz metin
        fontSize: 16,
        fontWeight: '600',
        letterSpacing: 0.5,
        marginLeft: 8, // İkon ile metin arasında boşluk
      },

    dateText: {
      color: '#94A3B8',
      fontSize: 14,
      fontWeight: '500',
    },
    detailTitle: {
      fontSize: 36,
      fontWeight: '800',
      color: '#D1B2FF',
      marginBottom: 24,
      letterSpacing: 0.5,
      lineHeight: 44,
    },
    content: {
      color: '#E2E8F0',
      marginBottom: 24,
      lineHeight: 28,
      fontSize: 16,
    },
    backButton: {
      marginTop: 24,
      backgroundColor: '#7C3AED',  
      padding: 14,
      borderRadius: 10,
      textAlign: 'center',
      width: 120,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 3,
    },
    backButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '600',
      letterSpacing: 0.5,
    },
    errorText: {
      color: '#EF4444',  
      fontSize: 16,
      marginBottom: 20,
      fontWeight: '500',
    },
    retryButton: {
      padding: 14,
      backgroundColor: '#D1B2FF',
      borderRadius: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 3,
    },
    retryText: {
      color: '#0F172A',
      fontSize: 16,
      fontWeight: '600',
      letterSpacing: 0.5,
    },
    blogContainer: {
      flex: 1,
      padding: 20,
      margin: 16,
      backgroundColor: '#1E293B',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: 'rgba(209, 178, 255, 0.1)',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 5,
    },
    blogContent: {
      color: '#1E293B',
      fontSize: 16,
      padding: 24,
      backgroundColor: '#F8F7FF', // Light purple tint
      minHeight: 200,
      borderRadius: 8,
      lineHeight: 24,
    },
  };
  
  export default styles;